name: weather_app
description: "Weather App created with the OpenWeather API"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cloud_firestore: ^5.2.1
  cupertino_icons: ^1.0.2
  firebase_core: ^3.3.0
  flutter_modular: ^6.3.3
  geolocator: ^12.0.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true
  assets:
    - assets/backgrounds/
